export type ScheduleType = {
  name: string;
  mon: string;
  tue: string;
  wed: string;
  thu: string;
  fri: string;
  sat: string;
};

export const schedule: ScheduleType[] = [
  {
    name: "KB NURUDHDHOLAM",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "KB AL-ANSHORIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "KB SEJAHTERA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "KB DARUL ILMI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "KB AT TAQWA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "TK ASSAJIDIN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "TK AISIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AS-SALAM KERSAMANAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA. AS SAADAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA/BA/TA ASSIBYAN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AL-FALAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AL-FALAH CIORAY HILIR",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 1 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 2 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 3 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 4 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS ASSIBYAN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS MUHAMMADIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS YPI PST GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MTSS YPI GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SMPS ISLAM TERPADU DARUL ABROR KERSAMANAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SMAS ISLAM PESANTREN GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
];
