export type ScheduleType = {
  name: string;
  mon: string;
  tue: string;
  wed: string;
  thu: string;
  fri: string;
  sat: string;
};

export const schedule: ScheduleType[] = [
  {
    name: "PAUD KB NURUDHDHOLAM",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD KB AL-ANSHORIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD KB SEJAHTERA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD DARUL ILMI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Libur",
    sat: "Libur",
  },
  {
    name: "PAUD KB AT TAQWA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "TK ASSAJIDIN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "TK AISIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA ASSALAM KERSAMANAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AS SAADAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA/BA/TA ASSIBYAN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AL-FALAH CIPATIK",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "RA AL-FALAH CIORAY HILIR",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 1 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 2 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 3 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SDN 4 NANJUNGJAYA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS ASSIBYAN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS MUHAMMADIYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MIS YPI PST GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "MTSS YPI GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SMP IT DARUL ABROR",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SMA ISLAM PESANTREN GALMASI",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "TK AL HIDAYAH 1",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD AL HIDAYAH",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD AL MAARIJ",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Libur",
    sat: "Libur",
  },
  {
    name: "PAUD KB SIRRUR ASROR",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD KB SEROJA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Libur",
    sat: "Libur",
  },
  {
    name: "PAUD KB FATHUL KHOER",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Masuk",
  },
  {
    name: "PAUD KB AT TAQWA WALURAN",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "PAUD KB AL JIHAD",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
  {
    name: "SPS DAHLIA",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Libur",
    sat: "Libur",
  },
  {
    name: "MTS SUKAMAJU",
    mon: "Masuk",
    tue: "Masuk",
    wed: "Masuk",
    thu: "Masuk",
    fri: "Masuk",
    sat: "Libur",
  },
];
